name: Rust CI
on:
  push:
    branches: [ main ]
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    name: Build
    strategy:
      matrix:
        toolchain: [stable, beta, nightly]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Set up Rust ${{matrix.toolchain}}
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{matrix.toolchain}}
          override: true
      - name: Check out code
        uses: actions/checkout@v2
      - name: Test
        run: |          
          cd rs
          cargo test
        shell: bash
